### PR TITLE
bump alpine version to 3.18.3

### PR DESCRIPTION
**Pull request by port19x**

### CODE REVIEW

**Comment by port19x** [comment]
Should work for the new 3.18.3, as no changes happened in the dependency-repo

**Comment by port19x** [comment]
You probably weren't notified of the PR, lemme ping @benpye

**Comment by port19x** [comment]
nvm I guess

**Comment by agarzon-orangerine** [comment]
Looks like the project is not being maintained anymore, you can have a fork and keep it running from there, people will follow you.

**Comment by benpye** [comment]
Sorry @port19x - I've had other commitments over the past few weeks, if you resubmit this the change looks okay.

**Pull request closed without merging**
